"""Phase 2.5 — opening-placement *practice/drill* mode (plan.md §6.4).

Two pure, testable entry points used by the practice UI:

* :func:`generate_puzzle` — produce a random opening puzzle for any of the three
  draft seats. The *prior* placements (the opponent's, and for ``FIRST_FINAL`` the
  user's own opener) are generated by the default policy and baked into an
  :class:`OpeningPlacementRequest`, so the puzzle is a self-contained input.

* :func:`grade_practice` — grade the user's chosen settlement(s)+road(s) against
  the heuristic optimum with a forgiving *tolerance band* (full credit when the
  pick is within a few percent of the best). Heuristic-only, so it is instant.

Grading model (kept deliberately simple and consistent across seats):

* Each placement is graded **sequentially** against the legal options the user
  actually faced. A settlement scores its points if its :func:`node_score` is
  within :data:`SETTLEMENT_BAND` of the best legal node; a road scores if it is
  within :data:`ROAD_BAND` of the best road *from the settlement the user chose*
  (so the road is judged "relative to your settlement", per the design).
* ``optimal_placements`` is the per-step model line (best response at each step),
  consistent with what each grade reports as optimal — that is what the UI draws.
* ``ranking`` carries the solver's own top recommendations (joint-optimised for
  the SECOND seat) as extra "go deeper" context.

The band thresholds are the only tunables and live here so they are easy to
adjust (Phase 4 may calibrate them against win-rate).
"""

from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Optional, Tuple

from catanatron import Action, ActionType, Color
from catanatron.models.enums import ActionPrompt

from catansolver.engine import game_from_board
from catansolver.engine.config import COLONIST_1V1, RulesConfig
from catansolver.engine.adapter import schema_to_map
from catansolver.io.schema import (
    BoardState,
    DraftSeat,
    OpeningPlacementRequest,
    Placement,
    PracticeResult,
    UnitGrade,
)

from .draft import PolicyFactory, _pick_road, default_policy, drive_to_user_decision, opening_prior_policy
from .heuristic import node_score
from .optimize import _legal_settlements, recommend_opening

Edge = Tuple[int, int]

# --------------------------------------------------------------------------- #
# Tunables (the practice scoring weights + tolerance band)
# --------------------------------------------------------------------------- #
PUZZLE_POINTS = 10.0  # a perfect answer scores this; other answers a fraction of it
SETTLEMENT_WEIGHT = 2  # a settlement is worth twice a road within the puzzle score
ROAD_WEIGHT = 1
SETTLEMENT_BAND = 0.93  # "within tolerance" if the spot scores >= 93% of the best legal spot
ROAD_BAND = 0.90  # "within tolerance" if the road scores >= 90% of the best legal road

USER_LABEL = "P1"
OPPONENT_LABEL = "P2"

#: how many settlements are already on the board when the user is asked to act
_PRIORS_BEFORE_DECISION: Dict[DraftSeat, int] = {
    DraftSeat.FIRST: 0,
    DraftSeat.SECOND: 1,
    DraftSeat.FIRST_FINAL: 3,
}

_MAX_DRAFT_PLIES = 16  # a 2-player draft is 8 plies; this is a safety cap


def _edge(v) -> Edge:
    return tuple(sorted(v))


def _far(edge: Edge, node: int) -> int:
    return edge[1] if edge[0] == node else edge[0]


# --------------------------------------------------------------------------- #
# Puzzle generation
# --------------------------------------------------------------------------- #
def generate_puzzle(
    board: BoardState,
    seat: DraftSeat,
    policy: PolicyFactory = opening_prior_policy,
    seed: Optional[int] = None,
    rules: RulesConfig = COLONIST_1V1,
) -> OpeningPlacementRequest:
    """Drive the draft with ``policy`` for both players up to the user's decision
    point, recording the placements made so far as the puzzle's *given* board.

    Returns an :class:`OpeningPlacementRequest` (board + seat + the prior
    placements) ready to be solved or graded — the user only has to supply the
    placement(s) the seat asks for.
    """
    game = game_from_board(
        board, [policy(Color.RED), policy(Color.BLUE)], rules=rules, seed=seed
    )
    first = game.state.current_color()
    user_cat = next(c for c in game.state.colors if c != first) if seat == DraftSeat.SECOND else first

    priors_needed = _PRIORS_BEFORE_DECISION[seat]
    settlements_by_cat: Dict[Color, List[int]] = defaultdict(list)
    roads_by_cat: Dict[Color, List[Edge]] = defaultdict(list)
    placed = 0

    for _ in range(_MAX_DRAFT_PLIES):
        prompt = game.state.current_prompt
        color = game.state.current_color()
        if (
            prompt == ActionPrompt.BUILD_INITIAL_SETTLEMENT
            and color == user_cat
            and placed >= priors_needed
        ):
            break  # the user's decision point — stop and hand the puzzle over
        before = len(game.state.actions)
        game.play_tick()
        for act in game.state.actions[before:]:
            if act.action_type == ActionType.BUILD_SETTLEMENT:
                settlements_by_cat[act.color].append(act.value)
                placed += 1
            elif act.action_type == ActionType.BUILD_ROAD:
                roads_by_cat[act.color].append(_edge(act.value))
    else:  # pragma: no cover - safety
        raise RuntimeError("draft generation did not reach the user's decision point")

    label_of = {user_cat: USER_LABEL}
    opponent_cat = next((c for c in game.state.colors if c != user_cat))
    label_of[opponent_cat] = OPPONENT_LABEL

    settlements = {label_of[c]: nodes for c, nodes in settlements_by_cat.items() if nodes}
    roads = {label_of[c]: edges for c, edges in roads_by_cat.items() if edges}

    return OpeningPlacementRequest(
        board=board,
        seat=seat,
        user_color=USER_LABEL,
        settlements=settlements,
        roads=roads,
    )


# --------------------------------------------------------------------------- #
# Grading
# --------------------------------------------------------------------------- #
def _rank(score: float, all_scores) -> int:
    """1-based rank of ``score`` (number of strictly-better options + 1)."""
    return sum(1 for s in all_scores if s > score) + 1


def _quality(chosen_score: float, all_scores) -> float:
    """How good a settlement choice is on a 0..1 scale, normalised over the legal
    spread (the worst legal option scores 0, the best scores 1). There are ~50
    legal nodes, so the spread is smooth and discriminating."""
    vals = list(all_scores)
    best, worst = max(vals), min(vals)
    if best - worst < 1e-9:
        return 1.0  # every option is equivalent
    return max(0.0, min(1.0, (chosen_score - worst) / (best - worst)))


def _road_quality(chosen_score: float, all_scores) -> float:
    """How good a road choice is on a 0..1 scale, as a *ratio to the best* road.

    A settlement has only ~3 legal roads, so spread-normalising (worst -> 0) is
    too coarse: the worst road typically still heads toward a spot ~70% as good,
    yet would score 0. Ratio-to-best credits a road for the value it actually
    captures, so a near-optimal road stays near-optimal."""
    best = max(all_scores, default=0.0)
    if best <= 0:
        return 1.0
    return max(0.0, min(1.0, chosen_score / best))


def _settlement_grade(
    index: int, chosen: int, scores: Dict[int, float], best_node: int
) -> UnitGrade:
    best = scores[best_node]
    chosen_score = scores.get(chosen, 0.0)
    rank = _rank(chosen_score, scores.values())
    return UnitGrade(
        kind="settlement",
        placement_index=index,
        chosen_node=chosen,
        optimal_node=best_node,
        chosen_score=round(chosen_score, 4),
        optimal_score=round(best, 4),
        pct_of_best=round(100.0 * chosen_score / best, 1) if best else 100.0,
        quality=round(_quality(chosen_score, scores.values()), 4),
        points=0.0,  # filled in once the puzzle's total weight is known
        rank=rank,
        n_options=len(scores),
        is_optimal=rank == 1,
        correct=best <= 0 or chosen_score >= best * SETTLEMENT_BAND,
    )


def _road_grade(
    index: int, chosen: Edge, scores: Dict[Edge, float], best_road: Edge
) -> UnitGrade:
    best = scores[best_road] if scores else 0.0
    chosen_score = scores.get(chosen, 0.0)
    rank = _rank(chosen_score, scores.values())
    return UnitGrade(
        kind="road",
        placement_index=index,
        chosen_edge=list(chosen),
        optimal_edge=list(best_road),
        chosen_score=round(chosen_score, 4),
        optimal_score=round(best, 4),
        pct_of_best=round(100.0 * chosen_score / best, 1) if best else 100.0,
        quality=round(_road_quality(chosen_score, scores.values()) if scores else 1.0, 4),
        points=0.0,
        rank=rank,
        n_options=len(scores),
        is_optimal=rank == 1,
        correct=best <= 0 or chosen_score >= best * ROAD_BAND,
    )


def _road_scores(game, catan_map, settlement: int) -> Dict[Edge, float]:
    """Score every legal initial road from ``settlement`` by the production value
    of the node it heads toward (the expansion-potential proxy)."""
    return {
        _edge(a.value): node_score(catan_map, _far(_edge(a.value), settlement))
        for a in game.state.playable_actions
        if a.action_type == ActionType.BUILD_ROAD
    }


def _model_line(work, catan_map, user: Color, n: int) -> List[Placement]:
    """The self-consistent greedy model answer: at each step take the best legal
    settlement and its best road, advancing the same line forward."""
    line: List[Placement] = []
    for _ in range(n):
        scores = {node: node_score(catan_map, node) for node in _legal_settlements(work)}
        best_node = max(scores, key=scores.get)
        work.execute(Action(user, ActionType.BUILD_SETTLEMENT, best_node))
        road_scores = _road_scores(work, catan_map, best_node)
        best_road = max(road_scores, key=road_scores.get)
        work.execute(_pick_road(work, best_road))
        line.append(Placement(settlement=best_node, road=list(best_road)))
    return line


def grade_practice(
    request: OpeningPlacementRequest,
    placements: List[Placement],
    policy: PolicyFactory = default_policy,
    rules: RulesConfig = COLONIST_1V1,
) -> PracticeResult:
    """Grade the user's opening ``placements`` for the puzzle ``request``.

    Each settlement/road is graded sequentially against the legal options the
    user faced (roads judged relative to the settlement the user actually chose).
    Returns per-unit grades, the model line to draw, and the solver's ranking.
    """
    catan_map = schema_to_map(request.board)
    ranking = recommend_opening(request, top_k=8, n_rollouts=0, policy=policy, rules=rules)

    game, user = drive_to_user_decision(request, policy, seed=0, rules=rules)

    # The model line is its own self-consistent greedy walk (always advance with
    # the best pick), so replaying it reproduces it exactly. Grading runs on a
    # separate walk that advances with the *user's* picks, so each step is judged
    # in the context the user actually created. The two coincide when the user
    # plays the model line — giving full marks for a perfect answer.
    optimal_placements = _model_line(game.copy(), catan_map, user, len(placements))

    grades: List[UnitGrade] = []
    work = game.copy()
    for i, pl in enumerate(placements):
        legal = _legal_settlements(work)
        scores = {n: node_score(catan_map, n) for n in legal}
        best_node = max(scores, key=scores.get)
        grades.append(_settlement_grade(i, pl.settlement, scores, best_node))

        # advance with the user's settlement (fall back to the best legal one if
        # the submitted node is illegal, so grading degrades gracefully)
        settle = pl.settlement if pl.settlement in scores else best_node
        work.execute(Action(user, ActionType.BUILD_SETTLEMENT, settle))

        road_scores = _road_scores(work, catan_map, settle)
        chosen_road = _edge(pl.road)
        best_road = max(road_scores, key=road_scores.get) if road_scores else chosen_road
        grades.append(_road_grade(i, chosen_road, road_scores, best_road))

        road = chosen_road if chosen_road in road_scores else best_road
        work.execute(_pick_road(work, road))

    # Distribute the 10-point puzzle score across units by weight, scaled by how
    # close each choice was to optimal (quality). A perfect answer scores 10.
    def _weight(g: UnitGrade) -> int:
        return SETTLEMENT_WEIGHT if g.kind == "settlement" else ROAD_WEIGHT

    total_weight = sum(_weight(g) for g in grades) or 1
    for g in grades:
        g.points = round(PUZZLE_POINTS * _weight(g) / total_weight * g.quality, 2)

    return PracticeResult(
        seat=request.seat,
        grades=grades,
        total_awarded=round(sum(g.points for g in grades), 2),
        total_max=PUZZLE_POINTS,
        is_optimal=all(g.is_optimal for g in grades),
        all_correct=all(g.correct for g in grades),
        optimal_placements=optimal_placements,
        ranking=ranking,
    )
